/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData admin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contribution = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData events = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData projects = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teams = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tutorials = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf3a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  
  
}
class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData edit = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}


class SocialMedia {
  SocialMedia._();

  static const _kFontFam = 'SocialMedia';
  static const _kFontPkg = null;

  static const IconData youtube = IconData(0xf16a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf308, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf31b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf31f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}


class Report {
  Report._();

  static const _kFontFam = 'Report';
  static const  _kFontPkg = null;

  static const IconData icon_ionic_md_open = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ionic_md_document = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}